name: Advance auto-merge queue

on:
  workflow_call:
    inputs:
      base-branch:
        type: string
        required: false
        default: main
    secrets:
      PR_GH_TOKEN:
        required: true

jobs:
  advance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Advance auto-merge queue
        uses: $/.github/actions/merge
        with:
          pr-token: ${{ secrets.PR_GH_TOKEN }}
          base-branch: ${{ inputs.base-branch }}
